require('dotenv').config();
const express = require('express');
var bodyParser = require('body-parser');
var morgan = require('morgan');
const cookieParser = require('cookie-parser');
const async = require('async');
const jwt = require("jsonwebtoken");
const mysql = require("mysql");
const bcrypt = require('bcryptjs');
const router = require('./route/main');
const clientRouter = require('./route/client');
const app = express();
const port = process.env.APP_PORT;
app.use(morgan('dev'));
const cron = require('node-cron');
const nodemailer = require('nodemailer');
const moment = require('moment');
var nl2br = require('nl2br');
const { promisify } = require('util');
var fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const cors = require('cors');
const axios = require('axios').default;
const custom_helpers = require('./customhelpers');
const path = require('path');
const hbs = require("hbs");
const staticPath = path.join(__dirname, "./public");
const templatePath = path.join(__dirname, "./templates/views");
const partialsPath = path.join(__dirname, "./templates/partials");
app.use('/public', express.static('public'));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
app.use(cors({origin: "*"}));
app.set("view engine", "hbs");
app.set("views", templatePath);
hbs.registerPartials(partialsPath);
app.use(express.static(staticPath));
app.use('/', router);
app.use('/clients', clientRouter);
app.use(function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
  res.setHeader('Access-Control-Allow-Credentials', true);
  next();
});
app.listen(port, () => {
  console.log(`Application Executing at http://localhost:${port}`);
  console.log(`Please open ngrok url by execute ./src/ngrok http ${port}`);
});